version: 1
services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: "python app.py"
    autoDeploy: true
